README.adoc, finish/src/main/java/io/openliberty/guides/sessions/SessionApplication.java, finish/src/main/java/io/openliberty/guides/sessions/SessionResource.java, finish/src/test/java/it/io/openliberty/guides/sessions/SessionResourceTest.java
Updates to sessions guide based on review feedback in issue #3.
=> Updates from review

.travis.yml, README.adoc, finish/pom.xml, finish/src/main/java/io/openliberty/guides/sessions/SessionApplication.java, finish/src/main/java/io/openliberty/guides/sessions/SessionResource.java, finish/src/main/liberty/config/hazelcast-config.xml, finish/src/main/liberty/config/server.xml, finish/src/test/java/it/io/openliberty/guides/sessions/SessionResourceTest.java, start/pom.xml
=> Addressed general guide issues

README.adoc
- Fixed some instructions while testing 
- Updated the URLs for the OpenAPI UI
=> Minor changes on the instructions

README.adoc
Review updates from issue #8 to provide more info in the intro and make the guide more microservice focused.
=> Review updates from issue #8

README.adoc, finish/src/main/java/io/openliberty/guides/cart/CartApplication.java, finish/src/main/java/io/openliberty/guides/cart/CartResource.java, finish/src/main/liberty/config/hazelcast-config.xml, finish/src/main/liberty/config/server.xml, finish/src/test/java/it/io/openliberty/guides/cart/CartSessionTest.java
- formatted classes to display better on the multipane
- fixed some multipane hotspot issues when there're multiple files in one section or subsection
=> Formatted classes for multipane

finish/pom.xml, start/pom.xml
Add jaxb core and api so the tests work on Java 11. Fix for #13.
=> Fix for tests on Java 11

.gitignore, README.adoc, finish/pom.xml, finish/src/main/liberty/config/hazelcast-config.xml
Hi,
I have gone through the guide. Overall, it was very smooth experience.  Thanks for the guide. 👏 
This is a small PR for some updates. You can take it partially or merge the full PR. 
- When I saw `make a POST request` on the guide but could not see an Curl then I realized that it was mentioning about UI. I added a clarification.
- Upgraded to latest hazelcast version 3.11.2
- removed password field. It is not needed for cluster formation[1] as of 3.8.2 and it is subject to be removed in future.[1],[2]
- Updated documentation to latest. `latest-dev` part in fact pointing to the dev version which is nightly snapshot.
- I added `verify hazelcast` part with some logs. I think that is important because if multicast has an issue then hazelcast will not be formed which would lead some …
=> Some Improvements about Hazelcast Session Guide

README.adoc, start/pom.xml
A couple minor updates I had after reading through the guide again.
=> Minor updates

README.adoc
- addressed issues raised in #20
=> Addressed user review feedback

README.adoc
This pr addresses the feedback raised by YK in issue #24.
=> Address feedback from YK

README.adoc
- incorporated id edits into the readme 
- ref to #45
=> Incorporated ID edits

.travis.yml
=> Merge qa to master: update travis script

.travis.yml, README.adoc
=> Merge qa to master: Prerequisites update

README.adoc
=> Merge qa to master: Remove MpProfile tag

.travis.yml, README.adoc, finish/Dockerfile, finish/pom.xml, finish/src/main/java/io/openliberty/guides/cart/CartResource.java, finish/src/main/liberty/config/server.xml, finish/src/test/java/it/io/openliberty/guides/cart/CartSessionIT.java, scripts/travisTest.sh, start/Dockerfile, start/pom.xml, start/src/test/java/it/io/openliberty/guides/cart/CartSessionIT.java
=> Merge qa to master: update to use simplified pom.xml and dev mode

finish/Dockerfile, start/Dockerfile
https://github.com/OpenLiberty/guides-common/issues/370
=>  Dockerfile update for best practices

finish/Dockerfile, start/Dockerfile
https://github.com/OpenLiberty/guides-common/issues/370
=> Dockerfile update for best practices

README.adoc, finish/pom.xml, start/pom.xml
=> Merge qa to master: update to mp3.3

.travis.yml, README.adoc, finish/pom.xml, start/pom.xml
=> Merge qa to master: fix travis automation

.travis.yml, scripts/travisTest.sh
Fix the .travis.yml
- https://github.com/OpenLiberty/guides-common/issues/497
- https://github.com/OpenLiberty/guides-common/issues/500
=> Fix the .travis.yml

scripts/travisTest.sh
Addressing https://github.com/OpenLiberty/guide-sessions/issues/90
=> Fix travis script

README.adoc, scripts/travisTest.sh
=> Merge qa to master: Update depcreated commands

README.adoc, finish/src/main/liberty/config/hazelcast-config.xml
=> Merge qa to master: add instruction for using minikube

README.adoc
=> Merge qa to master: Update README.adoc (#107)
